# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zümra Kavafoğlu Personal Web Page
email: zumra.kavafoglu@hacettepe.edu.tr
description: Zümra Kavafoğlu Personal Web Page
baseurl: "" # the subpath of your site, e.g. /blog
url: "zumrakavafoglu.github.io"
twitter_username: zumrakavafoglu
github_username:  zumrakavafoglu

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true

collections:
- projects
- publications
- news
- home-blocks
- bbs515-oop
- bbs515-weeks
- bca611-cg
- bca611-weeks