# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zümra Kavafoğlu Personal Web Page
email: zumra.kavafoglu@hacettepe.edu.tr
description: Automated automation software development 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mileva.com.tr"
twitter_username: mileva
github_username:  mileva

languages: ["en", "tr"]
exclude_from_localizations: ["assets"]

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true

collections:
- landing-items
- computer-graphics

plugins: 
  - jekyll-multiple-languages-plugin
